### PR TITLE
Cesare ferrari

### PR DESCRIPTION
**Pull request by cesareferrari**
MVP complete

### CODE REVIEW

**Comment by nateboyette** [comment]
Well done Cesare! Your code and the site looks great. I didn't see any mixins in the less file. Add two and implement them before I merge.  Let me know if they're there and I just overlooked them.

**Comment by cesareferrari** [comment]
@NLB510 

I did have mixins, but they were scattered around in the code and not labeled as mixins in the comments and I wasn't using () when I actually used the mixin in the other code. 

Now I added a comment section 'Mixins' and grouped them all together. They should be more visible. 

I am also using () after the mixin name. I read in the documentation that the use without parenthesis is deprecated but still works.

**Comment by nateboyette** [comment]
I see thanks for the clarification.

**Review by nateboyette — APPROVED** [review]
Great job!

**Pull request merged**
